### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Keisuke69xx** [serverless-operations/jeffy#14]
I get an error when trying to use sqs decorator.

You can reproduce this error with this simple code.

```
from jeffy.framework import get_app
app = get_app()

@app.handlers.sqs()
def handler(event, context):
    return event['messageId']
```

An error is the below.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jeffy/encoding/json.py", line 41, in decode
    return json.loads(payload.decode('utf-8'))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by horike37** [comment]
Thank you for reporting 👍 This root cause is that this decorator is only supported for JSON input. This should support for plain text as well.   
We will fix it.

**Comment by marcy-terui** [comment]
I think this is a specification issue, not a bug.
The encoding of the payload sent by SDK is different from the default encoding required by the handlers.
So I fixed the payloads to be sent and received transparently between SDK and handlers.
https://github.com/serverless-operations/jeffy/releases/tag/v1.1.0
